version: "{build}"

platform: x64

clone_folder: c:\gopath\src\github.com\dannypsnl\redux

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

build: false
deploy: false

test_script:
  - go get github.com/dannypsnl/assert
  - go test -v ./...
